
version : 0.2

phases:
  build:
    commands:
      - bash ../build.sh
  pre-build:
    commands:
      - docker login --username=$DOCKER_ID_USER --password=$DOCKER_PASS
artifacts:
  files:
    - commit_info.txt
